from pathlib import Path
import re

worker = Path('_worker.js')
s = worker.read_text(encoding='utf-8')

catalog = '''\nconst CHEMICAL_CATALOG = [\n  {product:'Amistar Top 325SC',active:'Azoxystrobin 200 g/L + Difenoconazole 125 g/L',crops:['coffee','pepper'],targets:['thán thư','rỉ sắt'],effects:'Thuốc trừ bệnh; hỗ trợ quản lý bệnh nấm theo nhãn.',source:'Danh mục thuốc BVTV hiện hành; phải đối chiếu nhãn trước mua/sử dụng.'},\n  {product:'Autopro 360SC',active:'Azocyclotin 100 g/L + Flonicamid 260 g/L',crops:['coffee'],targets:['rệp sáp'],effects:'Thuốc trừ sâu/rệp; dùng đúng đối tượng trên nhãn.',source:'Danh mục hiện hành; phải đối chiếu nhãn trước mua/sử dụng.'},\n  {product:'AU-Morax 60WG',active:'Cymoxanil 40% + Pyraclostrobin 20%',crops:['coffee'],targets:['rỉ sắt'],effects:'Thuốc trừ bệnh; hỗ trợ quản lý bệnh nấm theo nhãn.',source:'Danh mục hiện hành; phải đối chiếu nhãn trước mua/sử dụng.'}\n];\nconst chemicalSourceNote = 'Tham chiếu danh mục thuốc BVTV hiện hành của Việt Nam. AI chỉ đưa ứng viên; luôn đối chiếu nhãn thực tế, cây, đối tượng, liều và PHI trước mua/sử dụng.';\n'''
if 'const CHEMICAL_CATALOG' not in s:
    s = s.replace('\n\nasync function fetchWeather', '\n' + catalog + '\nasync function fetchWeather', 1)

reject_new = '''async function rejectRecommendation(env,recId){\n  if(!env.DB)throw new Error('D1 chưa được binding');\n  await env.DB.prepare("DELETE FROM tasks WHERE rec_id=? AND status!='DONE'").bind(recId).run();\n  await env.DB.prepare('DELETE FROM recommendations WHERE id=?').bind(recId).run();\n  return {ok:true};\n}\n'''
s = re.sub(r"async function rejectRecommendation\(env,recId\)\{.*?\}\nasync function pollTelegram", reject_new + '\nasync function pollTelegram', s, count=1, flags=re.S)

poll_new = '''async function pollTelegram(env){\n  if(!env.TELEGRAM_BOT_TOKEN||!env.TELEGRAM_CHAT_ID||!env.DB)return {processed:0};\n  const offset=Number(await getKv(env,'telegram_update_offset')||0);\n  const u=`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/getUpdates?timeout=0&allowed_updates=${encodeURIComponent(JSON.stringify(['callback_query','message']))}${offset?`&offset=${offset}`:''}`;\n  const r=await fetch(u); const d=await r.json().catch(()=>({}));\n  if(!r.ok||!d.ok)return {processed:0};\n  let processed=0,next=offset;\n  for(const upd of d.result||[]){\n    const updateId=Number(upd.update_id); const cb=upd.callback_query;\n    try{\n      if(cb){\n        const chatId=String(cb.message?.chat?.id||'');\n        if(chatId!==String(env.TELEGRAM_CHAT_ID)){ next=Math.max(next,updateId+1); continue; }\n        const data=String(cb.data||'');\n        if(data.startsWith('approve:')){\n          const out=await approveRecommendation(env,data.slice(8));\n          await telegramAnswer(env,cb.id,out.already?'Đã xử lý trước đó':'Đã duyệt và tạo lịch');\n          await telegramEdit(env,chatId,cb.message.message_id,`✅ ĐÃ DUYỆT\\n\\n${cb.message.text||'Khuyến cáo'}\\n\\n${out.created?.length||0} mốc lịch đã được tạo.`);\n        }else if(data.startsWith('reject:')){\n          await rejectRecommendation(env,data.slice(7));\n          await telegramAnswer(env,cb.id,'Đã từ chối và xóa khuyến cáo');\n          await telegramEdit(env,chatId,cb.message.message_id,`❌ ĐÃ TỪ CHỐI\\n\\n${cb.message.text||'Khuyến cáo'}\\n\\nKhuyến cáo và task chưa hoàn thành liên quan đã được xóa.`);\n        }else{ await telegramAnswer(env,cb.id,'Không nhận diện được thao tác'); }\n        next=Math.max(next,updateId+1); processed++; continue;\n      }\n      next=Math.max(next,updateId+1); processed++;\n    }catch(e){\n      try{await telegramAnswer(env,cb?.id,e.message||'Không xử lý được');}catch{}\n      break;\n    }\n  }\n  if(next>offset)await saveKv(env,'telegram_update_offset',next);\n  return {processed};\n}\n'''
s = re.sub(r"async function pollTelegram\(env\)\{.*?\}\n\nasync function runHourly", poll_new + '\nasync function runHourly', s, count=1, flags=re.S)

advice_new = '''function adviceSystem(){\n  return `Bạn là AI trợ lý nông vụ cho cà phê, hồ tiêu và cau tại Việt Nam. Ưu tiên IPM trước. Được phép đề xuất ứng viên thuốc từ CHEMICAL_CATALOG khi phù hợp; không bịa sản phẩm ngoài catalog. chemical[] phải có product,active,target,effect,dose,phi,why,source,verification. Khi chưa có nhãn xác minh dùng dose='Theo nhãn', phi='Theo nhãn', verification='UNVERIFIED'. Chỉ trả JSON thuần, không markdown, không suy luận nội bộ. Schema: {title,summary,assessment,risks[],checks[],nonChemical[],chemical[],weatherWindow,precautions[],confidence,nextSteps[]}. nextSteps[] gồm {daysFromNow,kind,title,notes}.`;\n}\nasync function generateAdvice(env, body){\n  const p=body.plant||{};\n  const text=JSON.stringify([body.observation||'',p.stage||'']).toLowerCase();\n  const matched=CHEMICAL_CATALOG.filter(x=>x.crops.includes(p.crop)).filter(x=>x.targets.some(t=>text.includes(String(t).toLowerCase())));\n  const prompt={plant:{...p,crop_name:cropName(p.crop),stage_name:stageName(p.crop,p.stage)},observation:body.observation||'',weather:body.weather||{},chemicalCandidates:matched,catalogSource:chemicalSourceNote,history:body.history||{},knowledge:body.knowledge||{}};\n  return callChatProvider(env,adviceSystem(),`Phân tích trường hợp sau và nếu phù hợp hãy đưa ứng viên hóa học từ catalog vào chemical[]. Không tự bịa liều/PHI. Dữ liệu: ${JSON.stringify(prompt)}`,body.image);\n}\n'''
s = re.sub(r"function adviceSystem\(\)\{.*?async function saveRecommendation", advice_new + '\nasync function saveRecommendation', s, count=1, flags=re.S)

daily_new = '''function dailySystem(){\n  return `Bạn là hệ thống điều phối Nông Vụ AI hằng ngày. Ưu tiên IPM. Có thể đề xuất ứng viên thuốc từ CHEMICAL_CATALOG khi phù hợp; không bịa sản phẩm ngoài catalog. chemical[] gồm product,active,target,effect,dose,phi,why,source,verification. Nếu chưa xác minh nhãn dùng dose='Theo nhãn', phi='Theo nhãn', verification='UNVERIFIED'. Chỉ trả JSON thuần: {dailySummary:string,alerts:[{plantId,level,title,message}],recommendations:[{plantId,title,summary,assessment,risks,checks,nonChemical,chemical,weatherWindow,precautions,confidence,nextSteps}]}. nextSteps[] gồm {daysFromNow,kind,title,notes}.`;\n}\n'''
s = re.sub(r"function dailySystem\(\)\{.*?\}\nasync function saveKv", daily_new + '\nasync function saveKv', s, count=1, flags=re.S)
s = s.replace("const prompt={date:new Date().toISOString(),plants,inventory:data.inventory.filter(x=>Number(x.label_verified)===1)};", "const prompt={date:new Date().toISOString(),plants,inventory:data.inventory.filter(x=>Number(x.label_verified)===1),chemicalCatalog:CHEMICAL_CATALOG,catalogSource:chemicalSourceNote};", 1)

routes = '''  if(url.pathname==='/api/recommendations/approve' && request.method==='POST'){const b=await request.json().catch(()=>({}));if(!b.id)return json({error:'Thiếu recommendation id'},400);return json(await approveRecommendation(env,b.id));}\n  if(url.pathname==='/api/recommendations/reject' && request.method==='POST'){const b=await request.json().catch(()=>({}));if(!b.id)return json({error:'Thiếu recommendation id'},400);return json(await rejectRecommendation(env,b.id));}\n'''
needle = "  if(url.pathname.startsWith('/api/recommendations/') && request.method==='DELETE'){"
if routes.strip() not in s: s=s.replace(needle, routes+needle, 1)
s=s.replace("  if(url.pathname.startsWith('/api/recommendations/') && request.method==='DELETE'){const rid=decodeURIComponent(url.pathname.split('/').pop()); if(!env.DB) return json({ok:false,local:true}); await env.DB.prepare(`DELETE FROM recommendations WHERE id=?`).bind(rid).run(); return json({ok:true});}", "  if(url.pathname.startsWith('/api/recommendations/') && request.method==='DELETE'){const rid=decodeURIComponent(url.pathname.split('/').pop()); if(!rid) return json({error:'Thiếu recommendation id'},400); return json(await rejectRecommendation(env,rid));}", 1)

worker.write_text(s,encoding='utf-8')
p=Path('wrangler.toml'); w=p.read_text(encoding='utf-8'); w=w.replace('crons = ["*/5 * * * *", "0 22 * * *"]','crons = ["* * * * *", "0 22 * * *"]'); p.write_text(w,encoding='utf-8')
print('patched',len(s))
