name = "nong-vu-ai"
main = "_worker.js"
compatibility_date = "2026-08-18"
workers_dev = true

[assets]
directory = "."
binding = "ASSETS"


[[d1_databases]]
binding = "DB"
database_name = "nong-vu-ai-db"
database_id = "86a70700-a042-402e-a3f9-c2c790ce87f7"

[vars]
OPENROUTER_MODEL = "openrouter/free"
OPENROUTER_VISION_MODEL = "openrouter/free"
GROQ_MODEL = "openai/gpt-oss-120b"
GROQ_VISION_MODEL = "qwen/qwen3.6-27b"

[triggers]
crons = ["* * * * *", "0 22 * * *"]
