(()=>{
'use strict';
const API='https://nong-vu-ai.draculacom1.workers.dev';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const parse=v=>{try{return JSON.parse(v||'{}')}catch{return {}}};
const crop={coffee:'Cà phê',pepper:'Hồ tiêu',areca:'Cau'};
const stageMap={
 coffee:{postharvest:{name:'Sau thu hoạch',focus:['Phục hồi bộ lá','rễ và đất','vệ sinh vườn'],nutrients:[['N','Phục hồi sinh khối','medium'],['P','Rễ và phục hồi','medium'],['K','Cân đối, tránh dư','low'],['Ca','Cấu trúc mô','medium'],['Mg','Diệp lục','medium'],['S','Chuyển hóa đạm','low'],['B','Theo dõi đọt non','low'],['Zn','Theo dõi sinh trưởng','low']]},shoot:{name:'Phục hồi – phát triển cành lá',focus:['Tạo cành hữu hiệu','bộ lá khỏe'],nutrients:[['N','Sinh trưởng cành lá','high'],['P','Rễ và chồi','medium'],['K','Cân đối tán','medium'],['Mg','Diệp lục','medium'],['Ca','Mô non','medium'],['S','Chuyển hóa đạm','medium'],['Zn','Đọt non','medium'],['B','Mô phân sinh','medium']]},floral:{name:'Phân hóa mầm hoa',focus:['Cây sung sức','quản lý N','ổn định ẩm đất'],nutrients:[['N','Không thúc quá mạnh','low'],['P','Mầm hoa và rễ','medium'],['K','Cân đối và chuyển hóa','high'],['Mg','Quang hợp','medium'],['Ca','Mô hoa','medium'],['B','Mầm hoa','high'],['Zn','Sinh trưởng sinh sản','medium'],['S','Cân đối dinh dưỡng','medium']]},flower:{name:'Ra hoa',focus:['Đồng đều ra hoa','giữ hoa','ẩm đất'],nutrients:[['N','Duy trì, tránh dư','low'],['P','Năng lượng','medium'],['K','Hoa và cân bằng nước','high'],['Ca','Độ bền mô','medium'],['B','Thụ phấn/đậu trái','high'],['Zn','Sinh trưởng sinh sản','medium'],['Mg','Quang hợp','medium']]},fruitset:{name:'Đậu quả',focus:['Giữ quả non','ổn định nước'],nutrients:[['N','Duy trì tán','medium'],['P','Đậu quả và năng lượng','medium'],['K','Giữ quả non','high'],['Ca','Độ bền mô quả','high'],['Mg','Quang hợp','medium'],['B','Đậu quả','high'],['Zn','Sinh trưởng quả','medium'],['S','Cân đối','low']]},fruit:{name:'Nuôi quả',focus:['Nuôi quả','giữ lá','tăng hiệu suất quang hợp'],nutrients:[['N','Duy trì vừa phải','medium'],['P','Năng lượng','low'],['K','Nuôi quả và chất lượng','high'],['Ca','Mô quả','high'],['Mg','Quang hợp','high'],['S','Protein/chuyển hóa','medium'],['B','Theo dõi chất lượng quả','medium'],['Zn','Theo dõi lá/đọt','medium']]},ripening:{name:'Quả phát triển – chín',focus:['Chất lượng quả','cân đối K','không thúc N'],nutrients:[['N','Tránh thúc chồi','low'],['P','Duy trì','low'],['K','Chất lượng quả','high'],['Ca','Độ bền mô','medium'],['Mg','Quang hợp','medium'],['B','Theo dõi','medium'],['S','Cân đối','low']]},preharvest:{name:'Chuẩn bị thu hoạch',focus:['PHI','an toàn','ổn định cây'],nutrients:[['N','Không thúc mạnh','low'],['K','Duy trì cân đối','medium'],['Ca','Độ bền mô','medium'],['Mg','Duy trì lá','medium'],['B','Theo dõi','low']] }},
 pepper:{recovery:{name:'Sau thu hoạch – phục hồi',focus:['rễ','đất','phục hồi dây'],nutrients:[['N','Phục hồi sinh khối','medium'],['P','Rễ','medium'],['K','Cân đối','medium'],['Ca','Rễ và mô','high'],['Mg','Lá','medium'],['S','Chuyển hóa','low'],['Zn','Sinh trưởng','medium'],['B','Theo dõi','low']]},canopy:{name:'Phát triển thân – cành',focus:['tán khỏe','đốt hữu hiệu'],nutrients:[['N','Sinh trưởng tán','high'],['P','Rễ/chồi','medium'],['K','Cân đối nước','medium'],['Ca','Mô non','medium'],['Mg','Lá','medium'],['B','Mô phân sinh','medium'],['Zn','Đọt','medium']]},flower:{name:'Ra hoa',focus:['đồng đều hoa','ẩm đất'],nutrients:[['N','Không dư','low'],['P','Hoa/rễ','medium'],['K','Hoa và nước','high'],['Ca','Mô hoa','medium'],['B','Hoa và đậu trái','high'],['Zn','Sinh trưởng sinh sản','medium'],['Mg','Quang hợp','medium']]},fruitset:{name:'Đậu trái',focus:['giữ trái non','ẩm đất'],nutrients:[['N','Duy trì','medium'],['P','Năng lượng','medium'],['K','Giữ trái','high'],['Ca','Mô quả','high'],['Mg','Lá','medium'],['B','Đậu trái','high'],['Zn','Quả non','medium']]},fruit:{name:'Nuôi trái',focus:['nuôi chùm','rễ khỏe','giữ lá'],nutrients:[['N','Vừa phải','medium'],['P','Duy trì','low'],['K','Nuôi chùm','high'],['Ca','Mô quả','high'],['Mg','Quang hợp','medium'],['B','Chất lượng quả','medium'],['Zn','Theo dõi','medium'],['S','Cân đối','medium']]},preharvest:{name:'Trước thu hoạch',focus:['PHI','an toàn','đồng đều'],nutrients:[['N','Không thúc','low'],['K','Chất lượng','medium'],['Ca','Độ bền mô','medium'],['Mg','Duy trì lá','medium']]},harvest:{name:'Thu hoạch',focus:['thu hái','vệ sinh'],nutrients:[['N','Không ưu tiên','low'],['K','Duy trì','low']]},post:{name:'Sau thu hoạch',focus:['vệ sinh','phục hồi'],nutrients:[['N','Phục hồi','medium'],['P','Rễ','medium'],['K','Cân đối','medium'],['Ca','Mô/rễ','medium'],['Mg','Lá','medium']]}},
 areca:{seedling:{name:'Cây con',focus:['rễ khỏe','ổn định tán'],nutrients:[['N','Tăng trưởng','medium'],['P','Rễ','high'],['K','cân đối','medium'],['Ca','Mô non','high'],['Mg','Lá','medium'],['Zn','Sinh trưởng','medium'],['B','Mô phân sinh','medium']]},juvenile:{name:'Kiến thiết cơ bản',focus:['thân lá','rễ'],nutrients:[['N','Sinh trưởng','high'],['P','Rễ','medium'],['K','Cân đối','medium'],['Ca','Mô','medium'],['Mg','Lá','medium'],['B','Đọt','medium'],['Zn','Sinh trưởng','medium']]},mature:{name:'Cây trưởng thành',focus:['duy trì tán','nuôi buồng'],nutrients:[['N','Duy trì','medium'],['P','Duy trì rễ','low'],['K','Nuôi buồng','high'],['Ca','Mô','medium'],['Mg','Lá','medium'],['B','Buồng/hoa','medium'],['Zn','Sinh trưởng sinh sản','medium']]},fruit:{name:'Mang buồng – nuôi trái',focus:['nuôi buồng','giảm rụng'],nutrients:[['N','Vừa phải','medium'],['P','Năng lượng','medium'],['K','Nuôi trái','high'],['Ca','Mô trái','high'],['Mg','Quang hợp','medium'],['B','Đậu/nuôi trái','high'],['Zn','Theo dõi','medium']]},harvest:{name:'Thu hoạch',focus:['thu hoạch','an toàn'],nutrients:[['N','Không ưu tiên','low'],['K','Duy trì','low']]}}
};
const sourceForms={
 N:['NPK có N phù hợp','Ure / nguồn N phù hợp'],P:['MAP','DAP / nguồn P phù hợp'],K:['K2SO4 (kali sunfat)','KNO3 hoặc nguồn K phù hợp'],Ca:['Canxi','Canxi hữu cơ/chelate tùy sản phẩm'],Mg:['MgSO4','Dolomite hoặc nguồn Mg phù hợp'],S:['MgSO4','Nguồn S phù hợp'],B:['Boron / Bo','Phân trung vi lượng có B'],Zn:['Kẽm / Zn','Trung vi lượng có Zn'],Fe:['Sắt / Fe','Vi lượng chelate nếu phù hợp'],Mn:['Mangan / Mn','Trung vi lượng có Mn']
};
const icons={
 leaf:'<svg viewBox="0 0 64 64"><path d="M55 9C31 10 12 19 12 38c0 9 7 16 16 16 19 0 28-19 27-45Z"/><path d="M11 53c10-16 19-24 38-35"/></svg>',
 flask:'<svg viewBox="0 0 64 64"><path d="M25 8h14M28 8v16l-17 27a4 4 0 0 0 3 6h36a4 4 0 0 0 3-6L36 24V8"/><path d="M19 47h26"/></svg>',
 sun:'<svg viewBox="0 0 64 64"><circle cx="32" cy="32" r="10"/><path d="M32 6v8M32 50v8M6 32h8M50 32h8M13 13l6 6M45 45l6 6M51 13l-6 6M19 45l-6 6"/></svg>',
 chart:'<svg viewBox="0 0 64 64"><path d="M9 54V18M9 54h46"/><path d="m15 43 12-11 9 7 14-20"/></svg>',
 bag:'<svg viewBox="0 0 64 64"><path d="M12 20h40v34H12z"/><path d="M22 20c0-7 4-12 10-12s10 5 10 12M20 32h24"/></svg>'
};
const css=`
#nv-old-tools{display:none!important}#nv-chemical-tab,#nv-regimen-tab{display:none!important}
#nvx-launch{position:fixed;right:16px;bottom:96px;z-index:9988;border:0;border-radius:18px;padding:12px 15px;background:linear-gradient(135deg,#0b7a48,#159f63);color:#fff;font-weight:900;box-shadow:0 14px 32px rgba(11,122,72,.28);display:flex;align-items:center;gap:8px}
#nvx-overlay{position:fixed;inset:0;z-index:9999;background:#f5f7fb;display:none;overflow:auto}
#nvx-overlay.on{display:block;animation:nvxIn .22s ease both}@keyframes nvxIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
.nvx-head{position:sticky;top:0;z-index:5;padding:17px 17px 12px;background:rgba(245,247,251,.92);backdrop-filter:blur(18px);border-bottom:1px solid #e1e5eb}.nvx-head-row{display:flex;justify-content:space-between;gap:10px;align-items:center}.nvx-title{font-size:29px;font-weight:950;letter-spacing:-.8px}.nvx-sub{color:#6f7783;margin-top:3px;font-size:13px}.nvx-close{width:42px;height:42px;border:0;border-radius:14px;background:#fff;box-shadow:0 5px 18px rgba(0,0,0,.08);font-size:24px}
.nvx-body{max-width:820px;margin:auto;padding:13px 14px 120px}.nvx-hero{position:relative;overflow:hidden;color:#fff;border-radius:24px;padding:18px;background:linear-gradient(135deg,#0b7a48,#29a76b);box-shadow:0 15px 34px rgba(9,104,58,.18)}.nvx-hero::after{content:"";position:absolute;width:180px;height:180px;right:-65px;top:-65px;border-radius:50%;background:rgba(255,255,255,.12)}.nvx-hero-art{position:absolute;right:18px;bottom:12px;width:78px;height:78px;opacity:.78}.nvx-hero-art svg,.nvx-icon svg{width:100%;height:100%;stroke:currentColor;fill:none;stroke-width:2.2;stroke-linecap:round;stroke-linejoin:round}.nvx-hero-k{font-size:11px;font-weight:850;letter-spacing:.1em;opacity:.82}.nvx-hero h2{margin:4px 90px 0 0;font-size:25px;line-height:1.05}.nvx-hero p{margin:8px 90px 0 0;font-size:12px;opacity:.9;line-height:1.45}
.nvx-tabs{display:flex;gap:8px;overflow:auto;padding:10px 0}.nvx-tab{white-space:nowrap;border:1px solid #e0e4ea;border-radius:999px;background:#fff;padding:9px 13px;font-weight:850}.nvx-tab.on{background:#0d7c4b;color:#fff;border-color:#0d7c4b}
.nvx-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.nvx-card{background:#fff;border:1px solid #e3e6ec;border-radius:20px;padding:15px;box-shadow:0 7px 25px rgba(22,35,52,.045);margin-top:10px}.nvx-stat{padding:14px;color:#fff;min-height:98px}.nvx-stat strong{display:block;font-size:26px}.nvx-stat span{font-size:11px;opacity:.82}.nvx-stat.green{background:linear-gradient(145deg,#0b7a48,#19a86a)}.nvx-stat.blue{background:linear-gradient(145deg,#116fe8,#48a5ff)}.nvx-stat.orange{background:linear-gradient(145deg,#f08a16,#ffb94e)}.nvx-stat.purple{background:linear-gradient(145deg,#6752d8,#9a7ff0)}
.nvx-section{display:flex;justify-content:space-between;align-items:center;gap:10px;margin:14px 2px 8px}.nvx-section h3{margin:0;font-size:17px}.nvx-muted{font-size:12px;color:#6f7681;line-height:1.5}
.nvx-focus{display:flex;flex-wrap:wrap;gap:7px}.nvx-pill{padding:7px 10px;border-radius:999px;background:#edf7f1;color:#17633f;font-size:11px;font-weight:850}.nvx-pill.warn{background:#fff3dc;color:#915b00}.nvx-pill.red{background:#ffebeb;color:#a92b28}
.nvx-nutrient{border:1px solid #e4e7ec;border-radius:17px;padding:12px;margin-top:8px;background:linear-gradient(180deg,#fff,#fbfcfd)}.nvx-n-top{display:flex;align-items:center;gap:9px}.nvx-icon{width:34px;height:34px;border-radius:11px;display:grid;place-items:center;background:#eaf6ef;color:#147d4d;flex:0 0 auto}.nvx-icon.orange{background:#fff1da;color:#b66a00}.nvx-icon.blue{background:#e9f2ff;color:#0a6fe8}.nvx-icon.purple{background:#efeaff;color:#6849d9}.nvx-n-name{font-weight:900}.nvx-level{margin-left:auto;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:900}.nvx-level.high{background:#ffe6e5;color:#b32822}.nvx-level.medium{background:#fff0d5;color:#956000}.nvx-level.low{background:#eaf6ef;color:#1c7147}.nvx-n-note{margin-top:8px;font-size:12px;color:#555d68}.nvx-sources{display:flex;flex-wrap:wrap;gap:6px;margin-top:7px}.nvx-source{font-size:10px;padding:5px 8px;border-radius:999px;background:#f0f2f5;color:#535b67}
.nvx-buy{display:grid;grid-template-columns:20px 1fr auto;gap:9px;align-items:start;padding:11px 0;border-top:1px solid #edf0f3}.nvx-buy:first-child{border-top:0}.nvx-buy input{width:20px;height:20px;accent-color:#16834f;margin-top:2px}.nvx-buy-name{font-weight:850}.nvx-buy-meta{font-size:11px;color:#6d7480;line-height:1.45;margin-top:2px}.nvx-owned{padding:4px 7px;border-radius:999px;font-size:10px;font-weight:900;background:#e8f8ee;color:#17643d}.nvx-need{padding:4px 7px;border-radius:999px;font-size:10px;font-weight:900;background:#fff0dc;color:#965d00}
.nvx-round{position:relative;padding:14px 0 14px 17px;border-left:3px solid #19a86a}.nvx-round+.nvx-round{margin-top:4px}.nvx-round-dot{position:absolute;left:-7px;top:16px;width:11px;height:11px;border-radius:50%;background:#19a86a;border:3px solid #fff;box-shadow:0 0 0 1px #19a86a}.nvx-round-top{display:flex;justify-content:space-between;gap:8px}.nvx-round-title{font-weight:900}.nvx-count{font-size:10px;color:#0c7a49;font-weight:900}.nvx-status{font-size:11px;color:#6d7480;margin-top:3px}.nvx-action{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.nvx-btn{border:0;border-radius:12px;padding:9px 11px;font-weight:850}.nvx-btn.primary{background:#0e7edb;color:#fff}.nvx-btn.light{background:#eef1f4}.nvx-btn.green{background:#e5f7ec;color:#19633f}
.nvx-empty{text-align:center;padding:24px 10px;color:#777}.nvx-note{margin-top:10px;padding:11px 12px;background:#f7f8fa;border-radius:13px;font-size:11px;line-height:1.5;color:#5d6672}
@media(min-width:720px){.nvx-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}
`;
function style(){if(document.getElementById('nvx-v27-style'))return;const s=document.createElement('style');s.id='nvx-v27-style';s.textContent=css;document.head.appendChild(s)}
function data(){return fetch(API+'/api/data',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error||'Không tải được dữ liệu');return d})}
function activePlant(d){return d.plants?.[0]||null}
function profile(p){return stageMap[p?.crop]?.[p?.stage]||null}
function levelLabel(x){return x==='high'?'Cao':x==='medium'?'Vừa':'Thấp'}
function sourceLines(n){return (sourceForms[n]||[]).map(x=>`<span class="nvx-source">${esc(x)}</span>`).join('')}
function nutrientCard(item){const [n,note,lvl]=item;const tone=lvl==='high'?'orange':n==='K'?'orange':n==='P'?'purple':'green';return `<div class="nvx-nutrient"><div class="nvx-n-top"><div class="nvx-icon ${tone}">${icons.leaf}</div><div class="nvx-n-name">${esc(n)}</div><span class="nvx-level ${lvl}">${levelLabel(lvl)}</span></div><div class="nvx-n-note">${esc(note)}</div><div class="nvx-sources">${sourceLines(n)}</div></div>`}
function inventoryOwned(d,label){const s=label.toLowerCase();return (d.inventory||[]).some(i=>Number(i.stock)>0 && (`${i.name||''} ${i.active||''} ${i.targets||''}`).toLowerCase().includes(s))}
function taskRounds(d){return (d.recs||[]).filter(r=>r.status!=='REJECTED').flatMap(r=>{const p=parse(r.payload);const steps=Array.isArray(p.nextSteps)?p.nextSteps:[];const tasks=(d.tasks||[]).filter(t=>t.rec_id===r.id).sort((a,b)=>(a.scheduled_at||'').localeCompare(b.scheduled_at||''));return steps.map((s,i)=>({rec:r,step:s,task:tasks[i]}))}).slice(0,8)}
function open(){style();ensure();document.getElementById('nvx-overlay').classList.add('on');render()}
function close(){document.getElementById('nvx-overlay')?.classList.remove('on')}
function ensure(){style();if(document.getElementById('nvx-overlay'))return;const b=document.createElement('button');b.id='nvx-launch';b.innerHTML='🧰 Nhu cầu & vật tư';b.onclick=open;document.body.appendChild(b);const o=document.createElement('div');o.id='nvx-overlay';o.innerHTML=`<div class="nvx-head"><div class="nvx-head-row"><div><div class="nvx-title">Nhu cầu & vật tư</div><div class="nvx-sub">Dinh dưỡng • BVTV • sinh học • phác đồ</div></div><button class="nvx-close" id="nvx-close">×</button></div></div><div class="nvx-body" id="nvx-body"></div>`;document.body.appendChild(o);document.getElementById('nvx-close').onclick=close}
async function render(){ensure();const body=document.getElementById('nvx-body');body.innerHTML='<div class="nvx-card">Đang tải dữ liệu…</div>';try{const d=await data();const p=activePlant(d);const prof=profile(p)||{name:p?.stage||'Giai đoạn hiện tại',focus:[],nutrients:[]};const rounds=taskRounds(d);const inv=d.inventory||[];const need=prof.nutrients.filter(x=>x[2]==='high').length;const owned=inv.filter(x=>Number(x.stock)>0).length;body.innerHTML=`<section class="nvx-hero"><div class="nvx-hero-k">NÔNG VỤ AI · KHUNG DINH DƯỠNG</div><h2>${esc(crop[p?.crop]||'Cây trồng')} · ${esc(prof.name)}</h2><p>${esc(prof.focus.join(' · ')||'Theo dõi giai đoạn và điều kiện thực tế')}</p><div class="nvx-hero-art">${icons.sun}</div></section><div class="nvx-grid"><div class="nvx-card nvx-stat green"><strong>${need}</strong><span>Dưỡng chất ưu tiên cao</span></div><div class="nvx-card nvx-stat blue"><strong>${prof.nutrients.length}</strong><span>Dưỡng chất đang theo dõi</span></div><div class="nvx-card nvx-stat orange"><strong>${owned}</strong><span>Vật tư đang có</span></div><div class="nvx-card nvx-stat purple"><strong>${rounds.length}</strong><span>Cữ đang theo dõi</span></div></div><div class="nvx-tabs"><button class="nvx-tab on" data-nvx-tab="need">🌿 Cây cần gì</button><button class="nvx-tab" data-nvx-tab="buy">🛒 Cần mua</button><button class="nvx-tab" data-nvx-tab="rounds">📋 Theo cữ</button></div><div id="nvx-panel"></div>`;bindTabs(body,d,p,prof,rounds);renderPanel('need',d,p,prof,rounds)}catch(e){body.innerHTML=`<div class="nvx-card" style="color:#a22">${esc(e.message)}</div>`}}
function bindTabs(root,d,p,prof,rounds){root.querySelectorAll('[data-nvx-tab]').forEach(b=>b.onclick=()=>{root.querySelectorAll('.nvx-tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderPanel(b.dataset.nvxTab,d,p,prof,rounds)})}
function renderPanel(tab,d,p,prof,rounds){const panel=document.getElementById('nvx-panel');if(!panel)return;if(tab==='need'){const risk=(d.recs||[]).filter(r=>r.status==='PENDING').slice(0,3).map(r=>`<span class="nvx-pill warn">⚠️ ${esc(r.title)}</span>`).join('');panel.innerHTML=`<div class="nvx-section"><h3>🌱 Cây đang cần gì?</h3></div><div class="nvx-card"><div class="nvx-focus">${prof.focus.map(x=>`<span class="nvx-pill">${esc(x)}</span>`).join('')}</div><div class="nvx-muted" style="margin-top:10px">Khuyến cáo theo giai đoạn là khung ưu tiên. Cần đối chiếu đất, lá, năng suất, thời tiết và quan sát thực tế trước khi bổ sung lượng lớn.</div></div><div class="nvx-card"><div class="nvx-section"><h3>Dinh dưỡng trọng tâm</h3><span class="nvx-muted">chất → mục tiêu → dạng có thể tìm</span></div>${prof.nutrients.map(nutrientCard).join('')||'<div class="nvx-empty">Chưa có cấu hình giai đoạn.</div>'}</div><div class="nvx-card"><div class="nvx-section"><h3>🛡️ Bảo vệ cây</h3></div><div class="nvx-focus">${risk||'<span class="nvx-pill">Chưa có khuyến cáo hóa học đang chờ duyệt</span>'}</div><div class="nvx-note">AI có thể đề xuất theo hoạt chất/nhóm tác dụng. Không tự phối trộn và không tự suy ra liều/PHI nếu chưa có nhãn hoặc nguồn xác minh.</div></div>`;return}
if(tab==='buy'){const list=[...prof.nutrients.filter(x=>x[2]==='high'),...prof.nutrients.filter(x=>x[2]==='medium')].map(x=>({label:x[0],note:x[1]}));panel.innerHTML=`<div class="nvx-card"><div class="nvx-section"><h3>🛒 Danh sách cần mua/bổ sung</h3><span class="nvx-muted">tick khi mày đã có</span></div>${list.map(x=>{const owned=inventoryOwned(d,sourceForms[x.label]?.[0]||x.label);return `<label class="nvx-buy"><input type="checkbox" ${owned?'checked':''} data-nvx-own="${esc(sourceForms[x.label]?.[0]||x.label)}"><div><div class="nvx-buy-name">${esc(x.label)} · ${esc(x.note)}</div><div class="nvx-buy-meta">Tìm theo thành phần: ${(sourceForms[x.label]||[x.label]).map(esc).join(' · ')}</div></div><span class="${owned?'nvx-owned':'nvx-need'}">${owned?'ĐÃ CÓ':'CẦN MUA'}</span></label>`}).join('')||'<div class="nvx-empty">Chưa có nhu cầu ưu tiên.</div>'}</div><div class="nvx-card"><div class="nvx-section"><h3>🧪 Hóa chất/hoạt chất</h3></div>${(d.inventory||[]).slice(0,20).map(i=>`<div class="nvx-buy"><div></div><div><div class="nvx-buy-name">${esc(i.name)}</div><div class="nvx-buy-meta">${esc(i.active||'')} · ${esc(i.targets||'')}</div></div><span class="${Number(i.stock)>0?'nvx-owned':'nvx-need'}">${Number(i.stock)>0?'ĐÃ CÓ':'CẦN MUA'}</span></div>`).join('')||'<div class="nvx-empty">Chưa có vật tư AI.</div>'}</div>`;panel.querySelectorAll('[data-nvx-own]').forEach(c=>c.onchange=()=>syncOwned(d,c.dataset.nvxOwn,c.checked));return}
const html=rounds.map((r,i)=>{const when=r.task?.scheduled_at;const done=r.task?.status==='DONE';const diff=when?new Date(when)-Date.now():0;const dd=when?(diff<0?'Đã đến hạn':Math.ceil(diff/86400000)<=1?'Đến trong 1 ngày':`Còn ${Math.ceil(diff/86400000)} ngày`):'';return `<div class="nvx-round"><span class="nvx-round-dot"></span><div class="nvx-round-top"><div class="nvx-round-title">Cữ ${i+1} · ${esc(r.step.title||r.step.kind||'Theo dõi')}</div><span class="nvx-count">${done?'ĐÃ XONG':esc(dd)}</span></div><div class="nvx-status">${esc(r.step.notes||'Theo dõi tình trạng cây trước khi quyết định cữ tiếp theo.')}</div><div class="nvx-action">${r.task?`<button class="nvx-btn green" data-nvx-update="${esc(r.task.id)}" data-nvx-plant="${esc(r.rec.plant_id)}">📷 Cập nhật tình trạng</button>`:''}</div></div>`}).join('');panel.innerHTML=`<div class="nvx-card"><div class="nvx-section"><h3>📋 Quy trình đang theo dõi</h3></div>${html||'<div class="nvx-empty">Chưa có cữ được lên lịch. Duyệt khuyến cáo AI để tạo lịch.</div>'}<div class="nvx-note">Sau mỗi cữ, cập nhật tình trạng cây. Hệ thống nên dùng kết quả mới để điều chỉnh cữ sau thay vì phun theo lịch một cách máy móc.</div></div>`;panel.querySelectorAll('[data-nvx-update]').forEach(b=>b.onclick=()=>updateAfterRound(d,b.dataset.nvxPlant,b.dataset.nvxUpdate));}
async function syncOwned(d,label,checked){const inv=d.inventory||[];const found=inv.find(i=>String(i.name||'').toLowerCase().includes(String(label).toLowerCase()));if(found){found.stock=checked?1:0}else if(checked){inv.push({id:crypto.randomUUID(),name:label,active:'',crop:'',targets:'',label_verified:0,dose:'Theo nhãn',phi:'Theo nhãn',stock:1,unit:'đv',created_at:new Date().toISOString()})}try{await fetch(API+'/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plants:d.plants,recs:d.recs,tasks:d.tasks,inventory:inv})});render()}catch{alert('Không lưu được trạng thái kho')}}
async function updateAfterRound(d,plantId,taskId){const p=d.plants.find(x=>x.id===plantId);const text=prompt('Cập nhật tình trạng cây sau cữ (lá, quả, bệnh/sâu, mức độ):',p?.last_observation||'');if(text===null)return;const body={plants:d.plants.map(x=>x.id===plantId?{...x,last_observation:text,last_check_at:new Date().toISOString(),updated_at:new Date().toISOString()}:x),inventory:d.inventory,recs:d.recs,tasks:d.tasks.map(t=>t.id===taskId?{...t,status:'DONE',completed_at:new Date().toISOString()}:t)};try{await fetch(API+'/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});alert('Đã cập nhật. AI sẽ dùng dữ liệu mới để điều chỉnh cữ sau.');render()}catch(e){alert('Không lưu được: '+e.message)}}
function init(){style();ensure();setTimeout(()=>{const o=document.getElementById('nvx-launch');if(location.hash==='#ai')o.style.display='flex'},1500);}
init();
})();
