(()=>{
'use strict';
const API='https://nong-vu-ai.draculacom1.workers.dev';
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const parse=v=>{try{return JSON.parse(v||'{}')}catch{return {}}};
const crop={coffee:'Cà phê',pepper:'Hồ tiêu',areca:'Cau'};
const nutrientForms={
 N:['NPK có N phù hợp','Ure / nguồn N phù hợp'],P:['MAP','DAP / nguồn P phù hợp'],K:['K2SO4 (kali sunfat)','KNO3 / nguồn K phù hợp'],Ca:['Canxi','Canxi chelate / hữu cơ tùy sản phẩm'],Mg:['MgSO4','Dolomite / nguồn Mg phù hợp'],S:['MgSO4','Nguồn S phù hợp'],B:['Bo / Boron','Trung vi lượng có B'],Zn:['Zn / Kẽm','Trung vi lượng có Zn'],Fe:['Fe / Sắt','Vi lượng chelate nếu phù hợp'],Mn:['Mn / Mangan','Trung vi lượng có Mn']
};
let data=null, root=null, filter='all';
function css(){if(document.getElementById('nvx-simple-style'))return;const s=document.createElement('style');s.id='nvx-simple-style';s.textContent=`
#nvx-overlay,#nv-kho-pro,#nvx-launch,#nv-kho-pro-btn{display:none!important}
#nv-simple{position:fixed;inset:0;z-index:10020;background:#f5f7fb;display:none;overflow:auto}
#nv-simple.on{display:block;animation:nvsIn .18s ease-out}@keyframes nvsIn{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:none}}
.nvs-head{position:sticky;top:0;z-index:4;background:rgba(245,247,251,.94);backdrop-filter:blur(16px);border-bottom:1px solid #e4e6eb;padding:15px 16px 12px}.nvs-head-row{display:flex;align-items:center;justify-content:space-between;gap:10px}.nvs-title{font-size:28px;font-weight:950;letter-spacing:-.6px}.nvs-sub{font-size:13px;color:#727780;margin-top:3px}.nvs-close{width:42px;height:42px;border:0;border-radius:14px;background:#fff;font-size:23px;box-shadow:0 4px 15px rgba(0,0,0,.06)}
.nvs-body{max-width:760px;margin:auto;padding:12px 14px 110px}.nvs-context{background:linear-gradient(135deg,#0e7f4d,#1aa46a);color:#fff;border-radius:18px;padding:15px 16px}.nvs-context small{opacity:.82;font-weight:800}.nvs-context b{display:block;font-size:23px;margin-top:3px}.nvs-context p{margin:5px 0 0;font-size:12px;opacity:.9}.nvs-summary{display:flex;gap:8px;margin-top:10px}.nvs-pill{flex:1;background:#fff;border:1px solid #e5e7ec;border-radius:14px;padding:10px 11px}.nvs-pill b{display:block;font-size:18px}.nvs-pill span{font-size:11px;color:#747981}
.nvs-section{margin-top:14px}.nvs-section h3{font-size:20px;margin:0 0 7px}.nvs-note{font-size:12px;color:#767a82;line-height:1.5;margin-bottom:8px}.nvs-filters{display:flex;gap:7px;overflow:auto;padding:1px 0 8px}.nvs-filter{border:1px solid #dde0e6;background:#fff;border-radius:999px;padding:8px 12px;font-weight:850;white-space:nowrap}.nvs-filter.on{background:#0d7d4b;color:#fff;border-color:#0d7d4b}
.nvs-list{display:flex;flex-direction:column;gap:8px}.nvs-item{background:#fff;border:1px solid #e5e7eb;border-radius:16px;padding:13px 14px}.nvs-row{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.nvs-name{font-weight:900;font-size:16px}.nvs-meta{font-size:12px;color:#71767f;margin-top:3px;line-height:1.45}.nvs-tag{display:inline-block;margin-top:7px;padding:4px 8px;border-radius:999px;background:#edf7f2;color:#146442;font-size:10px;font-weight:900}.nvs-high{border-left:4px solid #e28a10}.nvs-med{border-left:4px solid #2d86e9}.nvs-low{border-left:4px solid #9aa0a8}.nvs-check{width:21px;height:21px;accent-color:#0d7d4b;flex:none}.nvs-empty{padding:22px;text-align:center;color:#777;background:#fff;border:1px dashed #dfe2e7;border-radius:16px}.nvs-footer{margin-top:14px;padding:12px 14px;border-radius:14px;background:#fff8e8;color:#765d21;font-size:12px;line-height:1.5}
@media(min-width:700px){.nvs-summary{max-width:520px}.nvs-list{display:grid;grid-template-columns:1fr 1fr}.nvs-item{min-height:88px}}
`;
document.head.appendChild(s)}
async function load(){const r=await fetch(API+'/api/data');if(!r.ok)throw new Error(`Không tải được dữ liệu (${r.status})`);data=await r.json();return data}
function getPlant(){return (data?.plants||[])[0]||null}
function allChem(){const out=[];for(const r of data?.recs||[]){const p=parse(r.payload);for(const c of p.chemical||[])out.push({...c,status:r.status,recId:r.id})}const m=new Map();for(const c of out){const k=String(c.active||c.name||c.product||'').toLowerCase();if(k)m.set(k,c)}return [...m.values()]}
function nutrientList(p){const stage=(p?.stage||'').toLowerCase();const arr={
'postharvest':['N','P','Ca','Mg'],'shoot':['N','P','K','Ca','Mg','S','Zn','B'],'floral':['K','B','P','Mg','Ca','Zn'],'flower':['K','B','Ca','Mg','Zn'],'fruitset':['K','Ca','B','Mg','N','P'],'fruit':['K','Ca','Mg','B','N','Zn','S'],'ripening':['K','Ca','Mg','B'],'preharvest':['K','Ca','Mg']};
const keys=arr[stage]||['N','P','K','Ca','Mg','B','Zn'];
return keys.map((k,i)=>({k,level:i<3?'high':'medium',forms:nutrientForms[k]||[]}))}
function render(){if(!root)return;const p=getPlant();const ns=nutrientList(p);const chem=allChem();const inv=data?.inventory||[];const invMap=new Map(inv.map(x=>[String(x.name||'').toLowerCase(),x]));const stage=p?.stage_name||p?.stage||'Giai đoạn hiện tại';const high=ns.filter(x=>x.level==='high').length;const chemFiltered=filter==='nutrition'?[]:chem;const showNs=filter!=='bv';
root.innerHTML=`<div class="nvs-head"><div class="nvs-head-row"><div><div class="nvs-title">Nhu cầu & vật tư</div><div class="nvs-sub">Cây cần gì • dạng chất • hoạt chất • việc cần mua</div></div><button class="nvs-close" id="nvs-close">×</button></div></div><div class="nvs-body">
<div class="nvs-context"><small>KHUNG NHU CẦU HIỆN TẠI</small><b>${esc(crop[p?.crop]||'Cây trồng')} · ${esc(stage)}</b><p>Ưu tiên theo giai đoạn. Cần đối chiếu đất, lá, thời tiết và quan sát thực tế trước khi bổ sung.</p></div>
<div class="nvs-summary"><div class="nvs-pill"><b>${high}</b><span>Ưu tiên cao</span></div><div class="nvs-pill"><b>${ns.length}</b><span>Dinh dưỡng</span></div><div class="nvs-pill"><b>${chem.length}</b><span>Hoạt chất AI</span></div></div>
<div class="nvs-section"><div class="nvs-filters"><button class="nvs-filter ${filter==='all'?'on':''}" data-f="all">Tất cả</button><button class="nvs-filter ${filter==='nutrition'?'on':''}" data-f="nutrition">🌿 Dinh dưỡng</button><button class="nvs-filter ${filter==='bv'?'on':''}" data-f="bv">🧪 Hoạt chất BVTV</button></div></div>
${showNs?`<div class="nvs-section"><h3>🌿 Cây đang cần gì?</h3><div class="nvs-note">AI chỉ nêu nhu cầu/ưu tiên theo chất. Không khóa theo thương hiệu.</div><div class="nvs-list">${ns.map(x=>`<div class="nvs-item nvs-${x.level==='high'?'high':x.level==='medium'?'med':'low'}"><div class="nvs-row"><div><div class="nvs-name">${esc(x.k)}</div><div class="nvs-meta">Mục tiêu theo giai đoạn · ${x.level==='high'?'Ưu tiên cao':'Theo dõi / cân đối'}</div><span class="nvs-tag">Có thể tìm: ${esc(x.forms.join(' · '))}</span></div></div></div>`).join('')}</div></div>`:''}
${filter!=='nutrition'?`<div class="nvs-section"><h3>🧪 Hoạt chất AI đang theo dõi</h3><div class="nvs-note">Tập trung theo hoạt chất/đối tượng. Mày tự chọn sản phẩm thương mại có đúng hoạt chất và đối chiếu nhãn.</div><div class="nvs-list">${chemFiltered.map(c=>{const key=String(c.active||c.name||c.product||'').toLowerCase();const local=[...invMap.entries()].find(([n])=>n.includes(key)||key.includes(n));return `<div class="nvs-item"><div class="nvs-row"><div><div class="nvs-name">${esc(c.active||c.name||c.product||'Hoạt chất')}</div><div class="nvs-meta">${esc(c.target||c.targets||c.effect||'Theo khuyến cáo AI')} · ${esc(c.status||'')}</div><span class="nvs-tag">Không gắn thương hiệu</span></div><label title="Đã có"><input class="nvs-check" type="checkbox" ${local&&Number(local[1]?.stock)>0?'checked':''} data-have="${esc(local?.[1]?.id||'')}"/> </label></div></div>`}).join('')||'<div class="nvs-empty">Chưa có hoạt chất BVTV từ khuyến cáo AI.</div>'}</div></div>`:''}
<div class="nvs-footer">⚠️ Liều, PHI, phối trộn và thời gian tác dụng phải đối chiếu nhãn/nguồn chính thức. Hệ thống không tự suy diễn các thông số này.</div>
</div>`;
root.querySelector('#nvs-close').onclick=close;root.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{filter=b.dataset.f;render()});root.querySelectorAll('[data-have]').forEach(c=>c.onchange=()=>{if(!c.dataset.have){c.checked=false;alert('Mục này chưa có trong kho D1. Hãy chạy tư vấn để tạo vật tư trước.')}})}
async function open(){css();if(!root){root=document.createElement('div');root.id='nv-simple';document.body.appendChild(root)}root.classList.add('on');root.innerHTML='<div class="nvs-body"><div class="nvs-empty">Đang tải…</div></div>';try{await load();render()}catch(e){root.innerHTML=`<div class="nvs-body"><div class="nvs-empty">${esc(e.message)}</div></div>`}}
function close(){root?.classList.remove('on')}
function hook(){css();const old=document.getElementById('nv-clean-tool');if(old){old.style.display='grid';old.title='Nhu cầu & vật tư';old.textContent='🧰';old.onclick=open}const legacy=document.querySelectorAll('#nvx-launch,#nv-kho-pro-btn');legacy.forEach(x=>x.remove());}
hook();new MutationObserver(hook).observe(document.body,{childList:true,subtree:true});window.NVSimple={open,close};
})();