(()=>{"use strict";
const API="https://nong-vu-ai.draculacom1.workers.dev";
const esc=s=>String(s??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const crop={coffee:"Cà phê",pepper:"Hồ tiêu",areca:"Cau"};
const forms={N:["NPK phù hợp","Ure / nguồn N"],P:["MAP","DAP / nguồn P"],K:["K2SO4","KNO3 / nguồn K"],Ca:["Canxi","Canxi chelate"],Mg:["MgSO4","Dolomite / nguồn Mg"],S:["MgSO4","Nguồn S"],B:["Bo / Boron","Trung vi lượng có B"],Zn:["Zn / Kẽm","Trung vi lượng có Zn"]};
let data=null,mode="need";
function addStyle(){if(document.getElementById("nv-need-style"))return;const s=document.createElement("style");s.id="nv-need-style";s.textContent=`#nv-need-overlay{position:fixed;inset:0;background:#f6f7f9;z-index:10030;display:none;overflow:auto}#nv-need-overlay.on{display:block}.nvn-head{position:sticky;top:0;z-index:2;background:rgba(246,247,249,.96);backdrop-filter:blur(14px);padding:16px;border-bottom:1px solid #e4e6ea}.nvn-headrow{display:flex;align-items:center;justify-content:space-between}.nvn-title{font-size:27px;font-weight:900}.nvn-sub{font-size:12px;color:#777;margin-top:3px}.nvn-close{width:42px;height:42px;border:0;border-radius:14px;background:#fff;font-size:24px}.nvn-body{max-width:720px;margin:auto;padding:12px 14px 100px}.nvn-context{background:linear-gradient(135deg,#147b50,#2aa56d);color:#fff;border-radius:18px;padding:15px;margin-bottom:10px}.nvn-context small{opacity:.8;font-weight:800}.nvn-context b{display:block;font-size:23px;margin-top:3px}.nvn-tabs{display:flex;gap:8px;margin:10px 0}.nvn-tab{flex:1;border:1px solid #dfe2e7;background:#fff;border-radius:14px;padding:11px;font-weight:900}.nvn-tab.on{background:#147b50;color:#fff;border-color:#147b50}.nvn-card{background:#fff;border:1px solid #e3e6eb;border-radius:16px;padding:13px;margin-top:8px}.nvn-row{display:flex;justify-content:space-between;gap:10px}.nvn-name{font-weight:900;font-size:16px}.nvn-meta{font-size:12px;color:#70757d;line-height:1.45;margin-top:4px}.nvn-chip{display:inline-block;margin-top:7px;background:#edf7f2;color:#176743;padding:4px 8px;border-radius:999px;font-size:10px;font-weight:900}.nvn-check{width:21px;height:21px;accent-color:#147b50}.nvn-note{padding:12px;background:#fff8e7;color:#70591f;border-radius:14px;margin-top:10px;font-size:12px;line-height:1.5}.nvn-tool{width:40px;height:40px;border:1px solid rgba(60,60,67,.14);border-radius:12px;background:#fff;display:grid;place-items:center;box-shadow:0 2px 8px rgba(0,0,0,.05);font-size:19px}@media(min-width:700px){.nvn-body{padding-left:20px;padding-right:20px}}`;document.head.appendChild(s)}
async function load(){const r=await fetch(API+"/api/data");if(!r.ok)throw new Error("Không tải được dữ liệu");data=await r.json()}
function plant(){return data?.plants?.[0]||null}
function nutrients(p){const st=String(p?.stage||"").toLowerCase();const map={fruit:["K","Ca","Mg","B","N","Zn","S"],fruitset:["K","Ca","B","Mg","N","P"],flower:["K","B","Ca","Mg","Zn"],floral:["K","B","P","Mg","Ca","Zn"],shoot:["N","P","K","Ca","Mg","S","Zn","B"]};const keys=map[st]||["N","P","K","Ca","Mg","B","Zn"];return keys.map((k,i)=>({k,level:i<3?"Ưu tiên cao":"Theo dõi",forms:forms[k]||[]}))}
function actives(){const out=[],seen=new Set();for(const r of data?.recs||[]){let p={};try{p=JSON.parse(r.payload||"{}")}catch{}for(const c of p.chemical||[]){const a=String(c.active||c.name||c.product||"").trim();if(!a)continue;const key=a.toLowerCase();if(seen.has(key))continue;seen.add(key);out.push({name:a,target:c.target||c.targets||c.effect||"Theo khuyến cáo AI"})}}return out}
function render(){const p=plant(),ns=nutrients(p),cs=actives(),inv=data?.inventory||[],body=document.getElementById("nvn-body");if(!body)return;body.innerHTML="";const ctx=document.createElement("div");ctx.className="nvn-context";ctx.innerHTML=`<small>NHU CẦU HIỆN TẠI</small><b>${esc(crop[p?.crop]||"Cây trồng")} · ${esc(p?.stage_name||p?.stage||"Giai đoạn hiện tại")}</b><div style="font-size:12px;margin-top:4px;opacity:.9">Ưu tiên theo giai đoạn + dữ liệu thực tế. Không khóa theo thương hiệu.</div>`;body.appendChild(ctx);const tabs=document.createElement("div");tabs.className="nvn-tabs";tabs.innerHTML=`<button class="nvn-tab ${mode==='need'?'on':''}">🌿 Cây cần gì</button><button class="nvn-tab ${mode==='active'?'on':''}">🧪 Hoạt chất</button>`;body.appendChild(tabs);tabs.children[0].onclick=()=>{mode="need";render()};tabs.children[1].onclick=()=>{mode="active";render()};const list=mode==="need"?ns:cs;if(!list.length){const e=document.createElement("div");e.className="nvn-card";e.textContent=mode==="need"?"Chưa có dữ liệu nhu cầu.":"Chưa có hoạt chất từ khuyến cáo AI.";body.appendChild(e);return}list.forEach(x=>{const e=document.createElement("div");e.className="nvn-card";if(mode==="need")e.innerHTML=`<div class="nvn-row"><div><div class="nvn-name">${esc(x.k)}</div><div class="nvn-meta">${esc(x.level)} · Mục tiêu theo giai đoạn</div><span class="nvn-chip">Có thể tìm: ${esc(x.forms.join(" · "))}</span></div></div>`;else{const key=x.name.toLowerCase();const local=inv.find(v=>{const n=String(v.name||"").toLowerCase();return n.includes(key)||key.includes(n)});e.innerHTML=`<div class="nvn-row"><div><div class="nvn-name">${esc(x.name)}</div><div class="nvn-meta">${esc(x.target)}</div><span class="nvn-chip">Tự chọn sản phẩm đúng hoạt chất</span></div><input class="nvn-check" type="checkbox" ${local&&Number(local.stock)>0?"checked":""} title="Đã có"></div>`}body.appendChild(e)});const note=document.createElement("div");note.className="nvn-note";note.textContent="Liều, PHI, phối trộn và thời gian tác dụng chỉ dùng khi có nhãn/nguồn xác minh. Hệ thống không tự bịa các thông số này.";body.appendChild(note)}
async function open(){addStyle();const o=document.getElementById("nv-need-overlay");o.classList.add("on");document.getElementById("nvn-body").innerHTML='<div class="nvn-card">Đang tải…</div>';try{await load();render()}catch(e){document.getElementById("nvn-body").innerHTML=`<div class="nvn-card">${esc(e.message)}</div>`}}
function ensure(){addStyle();if(!document.getElementById("nv-need-overlay")){const o=document.createElement("div");o.id="nv-need-overlay";o.innerHTML='<div class="nvn-head"><div class="nvn-headrow"><div><div class="nvn-title">Nhu cầu & vật tư</div><div class="nvn-sub">Dinh dưỡng · hoạt chất · mua bổ sung</div></div><button class="nvn-close">×</button></div></div><div class="nvn-body" id="nvn-body"></div>';document.body.appendChild(o);o.querySelector(".nvn-close").onclick=()=>o.classList.remove("on")}const nav=document.querySelector(".nav-actions");if(nav&&!document.getElementById("nvn-tool")){const b=document.createElement("button");b.id="nvn-tool";b.className="nvn-tool";b.textContent="🧰";b.title="Nhu cầu & vật tư";b.onclick=open;nav.appendChild(b)}document.querySelectorAll("#nvx-launch,#nv-kho-pro-btn,#nv-clean-tool").forEach(e=>e.remove())}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",ensure,{once:true});else ensure();window.NVNeed={open};
})();